name: VPC Creation

on:
  workflow_dispatch:  # This allows the workflow to be triggered via the API
    inputs:
      project_id:
        description: 'The project ID'
        required: true
        type: string

jobs:
  vpc-creation:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform Plan
        run: terraform plan -var="project_id=${{ github.event.inputs.project_id }}"

      - name: Apply Terraform Apply
        run: terraform apply -auto-approve -var="project_id=${{ github.event.inputs.project_id }}"

      # - name: Apply Terraform Destroy
      #   run: terraform destroy -auto-approve -var="project_id=${{ github.event.inputs.project_id }}"
        # env:
        #   GOOGLE_CLOUD_KEYFILE_JSON: ${{ secrets.GCP_CREDENTIALS }}  # Replace with your secret for GCP credentials

