name: VPC Creation

on:
  workflow_dispatch:  # This allows the workflow to be triggered via the API

jobs:
  vpc-creation:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform Plan
        run: terraform plan 

      - name: Apply Terraform Apply
        run: terraform apply -auto-approve

      - name: Apply Terraform Destroy
        run: terraform destroy -auto-approve
        # env:
        #   GOOGLE_CLOUD_KEYFILE_JSON: ${{ secrets.GCP_CREDENTIALS }}  # Replace with your secret for GCP credentials

